apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-config
  #namespace: samrat-dev
data:
  APP_MESSAGE: "Welcome to MyBank!"
#data:
#  SPRING_PROFILES_ACTIVE: "prod"
#  DB_URL: "jdbc:mysql://mybank-db:3306/mybank"
#  DB_USER: "bank_user"
#  DB_PASSWORD: "securepassword"
