apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  namespace: samrat-dev
  labels:
    app: welcome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: ghcr.io/rajmcaitm/welcome/welcome:${GITHUB_SHA}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: welcome-config
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
#          readinessProbe:                     # ✅ Optional but strongly recommended
#            httpGet:
#              path: /mybank-app/welcome?name=Raj
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
          livenessProbe:                      # ✅ Optional (ensures restart if unhealthy)
            httpGet:
              path: /welcome-app/welcome
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret                   # ✅ ensures Docker Desktop can pull from GHCR
